name: kelolapps
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: ">=2.16.1 <3.0.0"
  sdk: ">=2.17.0-0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: lib/utils/fluk/flutx

  get: ^4.6.5
#  flutter_mobx: ^2.0.6+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1

  #BASE
  nb_utils: ^4.5.2
  google_fonts: ^2.3.2
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0

  #UI
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  package_info: ^2.0.2
  flutter_speed_dial: ^6.0.0
  dots_indicator: ^2.1.0
  flutter_svg: ^1.1.0
  badges: ^2.0.2
  carousel_slider: ^4.1.1

  #CONNECTIVITY
  http: ^0.13.4
  share_plus: ^4.0.4
  url_launcher: ^6.1.1
  jaguar_jwt: ^3.0.0
  collection: ^1.16.0

  # MAP
  google_maps_flutter: ^2.0.11
  geolocator: ^7.3.1
  geocoding: ^2.0.0

  # Common
  share: ^2.0.4
  html: ^0.15.0
  image_picker: ^0.8.5+3
  path_drawing: ^1.0.0

  smooth_page_indicator: 1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    # Used for general image
    - assets/public_image/
    - assets/kelolapps/
    - assets/store_image/
    - assets/promo/

    # Heading Fonts
    - assets/fonts/inter/

    # Description Fonts
    - assets/fonts/manrope/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Semibold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        # - asset: assets/fonts/manrope/Manrope-Thin.ttf
        #   weight: 100
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Semibold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
  #
  # For details regarding fontss from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#     fonts:
#       -family: Inter
#        fonts:

#     -  family: manrope
##        fonts:
#         - asset: assets/fonts/Manrope-Regular.otf
#         - asset: assets/font/Manrope-Light.ttf
#           weight: 100
#         - asset: assets/font/Manrope-ExtraLight.ttf
#             weight: 200
#         - asset: assets/font/Manrope-Light.ttf
#           weight: 300
#         - asset: assets/font/Manrope-Medium.ttf
#           weight: 500
#         - asset: assets/font/Manrope-Semibold.ttf
#           weight: 600
#         #          style: italic
#         - asset: assets/font/Manrope-Bold.ttf
#           weight: 700
